import fs from 'node:fs/promises';
import path from 'node:path';

import openapiTS, { astToString } from 'openapi-typescript';

const FILE_HEADER = `// AUTO-GENERATED by \`bc gen api-types\`
// Do not edit manually. Re-run \`bc gen api-types\` to refresh.
//
// Source: __SOURCE__
// Generated: __DATE__

`;

/**
 * OpenAPI 입력으로부터 TypeScript 타입 파일을 생성해 디스크에 쓴다.
 *
 * @param {object} args
 * @param {string|object} args.input  URL / 파일 경로 / 이미 파싱된 OpenAPI 객체
 * @param {string} args.outFile       절대/상대 경로
 * @param {string} args.sourceLabel   파일 헤더 주석에 표기할 출처 문자열
 * @returns {{ outFile: string, bytes: number }}
 */
export async function generateApiTypes({ input, outFile, sourceLabel }) {
  // openapi-typescript v7: 입력은 URL 객체, 파싱된 객체, 또는 path 문자열을 받음.
  // 우리가 받은 input 이 URL 문자열이면 URL 인스턴스로, 파일 경로면 그대로 넘김.
  let sdkInput = input;
  if (typeof input === 'string' && /^https?:\/\//.test(input)) {
    sdkInput = new URL(input);
  } else if (typeof input === 'string') {
    sdkInput = path.resolve(input);
  }

  const ast = await openapiTS(sdkInput);
  const code = astToString(ast);

  const header = FILE_HEADER
    .replace('__SOURCE__', sourceLabel ?? String(input))
    .replace('__DATE__', new Date().toISOString());

  const final = header + code + (code.endsWith('\n') ? '' : '\n');

  await fs.mkdir(path.dirname(outFile), { recursive: true });
  await fs.writeFile(outFile, final, 'utf8');
  return { outFile, bytes: Buffer.byteLength(final, 'utf8') };
}
